### ISSUE TITLE
Discuss other ways to visualize activity etc

### ISSUE THREAD

**Issue by choldgraf** [docathon/docathon#73]
Check out this page I threw together here: https://bids.github.io/docathon/pages/projects/projects.html

Any other ways that we can visualize information? Maybe by user? Either way, once we're happy with this we should send it out there. Maybe it'll encourage a few other projects to sign up. @Carreau @NelleV @teonbrooks @mrzv @stefanv

**Comment by teonbrooks** [comment]
I like this graph. hmm...this is tough because these metrics will all have their shortcoming. with commits, you could argue that you may make few commits when writing documentation since it is a bit more straightforward than code. 

I was thinking lines changed might be a good option as well. you could do by user and it would be a similar graph as the project activity one but for the docathon

**Comment by choldgraf** [comment]
there does appear to be the ability to look at lines changed, @stefanv was suggesting the same thing. It's a bit more complicated with the calls to github API though. Depends on whether somebody has time to take a stab at implementing it, but it shouldn't be too hard
